config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'rodadas#index'
  
  resources :pontuacaos
  resources :rodadas
  resources :cartoleiros
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cartoleiro.rb
class Cartoleiro < ApplicationRecord
  has_many :pontuacaos
  has_many :rodadas, through: :pontuacaos
end

app/models/pontuacao.rb
class Pontuacao < ApplicationRecord
  belongs_to :cartoleiro
  belongs_to :rodada
end

app/models/rodada.rb
class Rodada < ApplicationRecord
  has_many :pontuacaos
  has_many :cartoleiros, through: :pontuacaos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cartoleiros_controller.rb
class CartoleirosController < ApplicationController
  before_action :set_cartoleiro, only: [:show, :edit, :update, :destroy]

  # GET /cartoleiros
  # GET /cartoleiros.json
  def index
    @cartoleiros = Cartoleiro.all
  end

  # GET /cartoleiros/1
  # GET /cartoleiros/1.json
  def show
  end

  # GET /cartoleiros/new
  def new
    @cartoleiro = Cartoleiro.new
  end

  # GET /cartoleiros/1/edit
  def edit
  end

  # POST /cartoleiros
  # POST /cartoleiros.json
  def create
    @cartoleiro = Cartoleiro.new(cartoleiro_params)

    respond_to do |format|
      if @cartoleiro.save
        format.html { redirect_to @cartoleiro, notice: 'Cartoleiro was successfully created.' }
        format.json { render :show, status: :created, location: @cartoleiro }
      else
        format.html { render :new }
        format.json { render json: @cartoleiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cartoleiros/1
  # PATCH/PUT /cartoleiros/1.json
  def update
    respond_to do |format|
      if @cartoleiro.update(cartoleiro_params)
        format.html { redirect_to @cartoleiro, notice: 'Cartoleiro was successfully updated.' }
        format.json { render :show, status: :ok, location: @cartoleiro }
      else
        format.html { render :edit }
        format.json { render json: @cartoleiro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cartoleiros/1
  # DELETE /cartoleiros/1.json
  def destroy
    @cartoleiro.destroy
    respond_to do |format|
      format.html { redirect_to cartoleiros_url, notice: 'Cartoleiro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cartoleiro
      @cartoleiro = Cartoleiro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cartoleiro_params
      params.require(:cartoleiro).permit(:time, :nome, :camisa)
    end
end

app/controllers/pontuacaos_controller.rb
class PontuacaosController < ApplicationController
  before_action :set_pontuacao, only: [:show, :edit, :update, :destroy]
  
  skip_before_filter  :verify_authenticity_token

  # GET /pontuacaos
  # GET /pontuacaos.json
  def index
    @pontuacaos = Pontuacao.all
  end

  # GET /pontuacaos/1
  # GET /pontuacaos/1.json
  def show
  end

  # GET /pontuacaos/new
  def new
    @pontuacao = Pontuacao.new
  end

  # GET /pontuacaos/1/edit
  def edit
  end

  # POST /pontuacaos
  # POST /pontuacaos.json
  def create
    @pontuacao = Pontuacao.new(pontuacao_params)

    respond_to do |format|
      if @pontuacao.save
        format.html { redirect_to @pontuacao, notice: 'Pontuacao was successfully created.' }
        format.json { render :show, status: :created, location: @pontuacao }
      else
        format.html { render :new }
        format.json { render json: @pontuacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pontuacaos/1
  # PATCH/PUT /pontuacaos/1.json
  def update
    respond_to do |format|
      if @pontuacao.update(pontuacao_params)
        format.html { redirect_to @pontuacao, notice: 'Pontuacao was successfully updated.' }
        format.json { render :show, status: :ok, location: @pontuacao }
      else
        format.html { render :edit }
        format.json { render json: @pontuacao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pontuacaos/1
  # DELETE /pontuacaos/1.json
  def destroy
    @pontuacao.destroy
    respond_to do |format|
      format.html { redirect_to pontuacaos_url, notice: 'Pontuacao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pontuacao
      @pontuacao = Pontuacao.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pontuacao_params
      params.require(:pontuacao).permit(:cartoleiro_id, :rodada_id, :pontos, :posicao)
    end
end

app/controllers/rodadas_controller.rb
class RodadasController < ApplicationController
  before_action :set_rodada, only: [:show, :edit, :update, :destroy]
  
  skip_before_filter  :verify_authenticity_token

  # GET /rodadas
  # GET /rodadas.json
  def index
    @rodadas = Rodada.all
    @cartoleiros = Cartoleiro.all
  end

  # GET /rodadas/1
  # GET /rodadas/1.json
  def show
  end

  # GET /rodadas/new
  def new
    @rodada = Rodada.new
  end

  # GET /rodadas/1/edit
  def edit
  end

  # POST /rodadas
  # POST /rodadas.json
  def create
    @rodada = Rodada.new(rodada_params)

    respond_to do |format|
      if @rodada.save
        format.html { redirect_to @rodada, notice: 'Rodada was successfully created.' }
        format.json { render :show, status: :created, location: @rodada }
      else
        format.html { render :new }
        format.json { render json: @rodada.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rodadas/1
  # PATCH/PUT /rodadas/1.json
  def update
    respond_to do |format|
      if @rodada.update(rodada_params)
        format.html { redirect_to @rodada, notice: 'Rodada was successfully updated.' }
        format.json { render :show, status: :ok, location: @rodada }
      else
        format.html { render :edit }
        format.json { render json: @rodada.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rodadas/1
  # DELETE /rodadas/1.json
  def destroy
    @rodada.destroy
    respond_to do |format|
      format.html { redirect_to rodadas_url, notice: 'Rodada was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rodada
      @rodada = Rodada.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rodada_params
      params.require(:rodada).permit(:nome)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoleiros_helper.rb
module CartoleirosHelper
end

app/helpers/pontuacaos_helper.rb
module PontuacaosHelper
end

app/helpers/rodadas_helper.rb
module RodadasHelper
end

app/views/cartoleiros/_form.html.erb
<%= form_for(cartoleiro) do |f| %>
  <% if cartoleiro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cartoleiro.errors.count, "error") %> prohibited this cartoleiro from being saved:</h2>

      <ul>
      <% cartoleiro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :camisa %>
    <%= f.check_box :camisa %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cartoleiros/edit.html.erb
<h1>Editing Cartoleiro</h1>

<%= render 'form', cartoleiro: @cartoleiro %>

<%= link_to 'Show', @cartoleiro %> |
<%= link_to 'Back', cartoleiros_path %>

app/views/cartoleiros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cartoleiros</h1>

<table>
  <thead>
    <tr>
      <th>Time</th>
      <th>Nome</th>
      <th>Camisa</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cartoleiros.each do |cartoleiro| %>
      <tr>
        <td><%= cartoleiro.time %></td>
        <td><%= cartoleiro.nome %></td>
        <td><%= cartoleiro.camisa %></td>
        <td><%= link_to 'Show', cartoleiro %></td>
        <td><%= link_to 'Edit', edit_cartoleiro_path(cartoleiro) %></td>
        <td><%= link_to 'Destroy', cartoleiro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cartoleiro', new_cartoleiro_path %>

app/views/cartoleiros/new.html.erb
<h1>New Cartoleiro</h1>

<%= render 'form', cartoleiro: @cartoleiro %>

<%= link_to 'Back', cartoleiros_path %>

app/views/cartoleiros/show.html.bkp.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Time:</strong>
  <%= @cartoleiro.time %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @cartoleiro.nome %>
</p>

<p>
  <strong>Camisa:</strong>
  <%= @cartoleiro.camisa %>
</p>

<%= link_to 'Edit', edit_cartoleiro_path(@cartoleiro) %> |
<%= link_to 'Back', cartoleiros_path %>

app/views/cartoleiros/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1><%= "#{@cartoleiro.time} - #{@cartoleiro.nome}" %></h1>
  
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="bg-primary h3">
        <th>Rodada</th>
        <th>Classificação</th>
        <th>Pontuação</th>
      </tr>
    </thead>

    <tbody>
      <% @cartoleiro.pontuacaos.sort_by {|obj| obj.rodada_id}.each do |pontuacao| %>
        <tr class="h3">
          <td><%= link_to "#{pontuacao.rodada_id} ª Rodada", rodada_path(pontuacao.rodada_id) %></td>
          <td><%= pontuacao.posicao %>º</td>
          <td><%= number_with_precision pontuacao.pontos, :precision => 2 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>

  <%= line_chart @cartoleiro.pontuacaos.select(:rodada_id, :pontos).sort_by{|obj| obj.rodada_id}.map{|p| ["#{p.rodada_id}ª Rodada", p.pontos]}, height: "600px" %>
  
  <footer class="footer">
    <nav>
      <h4><%= link_to "Voltar",   root_path %></h4>
    </nav>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cartoleiros - Liga Igreja de Cristo RMBH</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi" %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pontuacaos/_form.html.erb
<%= form_for(pontuacao) do |f| %>
  <% if pontuacao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pontuacao.errors.count, "error") %> prohibited this pontuacao from being saved:</h2>

      <ul>
      <% pontuacao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cartoleiro_id %>
    <%= f.number_field :cartoleiro_id %>
  </div>

  <div class="field">
    <%= f.label :rodada_id %>
    <%= f.number_field :rodada_id %>
  </div>

  <div class="field">
    <%= f.label :pontos %>
    <%= f.text_field :pontos %>
  </div>

  <div class="field">
    <%= f.label :posicao %>
    <%= f.number_field :posicao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pontuacaos/edit.html.erb
<h1>Editing Pontuacao</h1>

<%= render 'form', pontuacao: @pontuacao %>

<%= link_to 'Show', @pontuacao %> |
<%= link_to 'Back', pontuacaos_path %>

app/views/pontuacaos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pontuacaos</h1>

<table>
  <thead>
    <tr>
      <th>Cartoleiro</th>
      <th>Rodada</th>
      <th>Pontos</th>
      <th>Posicao</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pontuacaos.each do |pontuacao| %>
      <tr>
        <td><%= pontuacao.cartoleiro_id %></td>
        <td><%= pontuacao.rodada_id %></td>
        <td><%= pontuacao.pontos %></td>
        <td><%= pontuacao.posicao %></td>
        <td><%= link_to 'Show', pontuacao %></td>
        <td><%= link_to 'Edit', edit_pontuacao_path(pontuacao) %></td>
        <td><%= link_to 'Destroy', pontuacao, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pontuacao', new_pontuacao_path %>

app/views/pontuacaos/new.html.erb
<h1>New Pontuacao</h1>

<%= render 'form', pontuacao: @pontuacao %>

<%= link_to 'Back', pontuacaos_path %>

app/views/pontuacaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cartoleiro:</strong>
  <%= @pontuacao.cartoleiro_id %>
</p>

<p>
  <strong>Rodada:</strong>
  <%= @pontuacao.rodada_id %>
</p>

<p>
  <strong>Pontos:</strong>
  <%= @pontuacao.pontos %>
</p>

<p>
  <strong>Posicao:</strong>
  <%= @pontuacao.posicao %>
</p>

<%= link_to 'Edit', edit_pontuacao_path(@pontuacao) %> |
<%= link_to 'Back', pontuacaos_path %>

app/views/rodadas/_form.html.erb
<%= form_for(rodada) do |f| %>
  <% if rodada.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rodada.errors.count, "error") %> prohibited this rodada from being saved:</h2>

      <ul>
      <% rodada.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rodadas/edit.html.erb
<h1>Editing Rodada</h1>

<%= render 'form', rodada: @rodada %>

<%= link_to 'Show', @rodada %> |
<%= link_to 'Back', rodadas_path %>

app/views/rodadas/index.html.bkp.erb
<p id="notice"><%= notice %></p>

<h1>Rodadas</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rodadas.each do |rodada| %>
      <tr>
        <td><%= rodada.nome %></td>
        <td><%= link_to 'Show', rodada %></td>
        <td><%= link_to 'Edit', edit_rodada_path(rodada) %></td>
        <td><%= link_to 'Destroy', rodada, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rodada', new_rodada_path %>

app/views/rodadas/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1>Classificação Final 2º Turno</h1>
  <h2 class="text-danger">Parabéns, <strong>Raposão 3000</strong>! Campeão da disputa da camisa da Liga Igreja de Cristo - RMBH!</h2>
  <h2 class="text-danger">Obrigado a todos pela participação! Foi bom demais, e ano que vem tem mais!</h2>
  <h2 class="text-primary">Que o Senhor abençoe a todos!</h2>
  
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="bg-primary h3">
        <th>Classificação</th>
        <th>Time</th>
        <th>Disputa a camisa?</th>
        <th>Pontos</th>
      </tr>
    </thead>
  
    <tbody>
      <% @cartoleiros.sort_by{|obj| obj.pontuacaos.to_a.sum(&:pontos)}.reverse.each_with_index do |cartoleiro, index| %>
        <tr class="h3">
          <td><%= index +1 %>º</td>
          <td><%= link_to cartoleiro.time, cartoleiro_path(cartoleiro.id) %></td>
          <td><%= cartoleiro.camisa ? "Sim": "Não"  %></td>
          <td><%= number_with_precision(cartoleiro.pontuacaos.to_a.sum(&:pontos), :precision => 2) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  
  <%= line_chart @cartoleiros.map{|ct|{name: ct.time, data: ct.pontuacaos.sort_by{|r| r[:rodada_id] }.map{|p| ["#{p.rodada_id}ª Rodada", p.pontos]}}}, height: "800px" %>
  
</div>

app/views/rodadas/new.html.erb
<h1>New Rodada</h1>

<%= render 'form', rodada: @rodada %>

<%= link_to 'Back', rodadas_path %>

app/views/rodadas/show.html.bkp.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @rodada.nome %>
</p>

<%= link_to 'Edit', edit_rodada_path(@rodada) %> |
<%= link_to 'Back', rodadas_path %>

app/views/rodadas/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h1><%= @rodada.nome %></h1>
  
  <div class="table-responsive">
  <table class="table">
    <thead>
      <tr class="bg-primary h3">
        <th>Classificação</th>
        <th>Time</th>
        <th>Disputa a camisa?</th>
        <th>Pontos</th>
      </tr>
    </thead>
  
    <tbody>
      
      <% @rodada.pontuacaos.sort_by {|obj| obj.posicao}.each do |pontuacao| %>
        <tr class="h3">
          <td><%= pontuacao.posicao %>º</td>
          <td><%= link_to pontuacao.cartoleiro.time, cartoleiro_path(pontuacao.cartoleiro.id) %></td>
          <td><%= pontuacao.cartoleiro.camisa ? "Sim": "Não"  %></td>
          <td><%= number_with_precision pontuacao.pontos, :precision => 2 %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
  
  <%= column_chart @rodada.pontuacaos.sort_by{|obj| obj.rodada_id}.map{|p| [p.cartoleiro.time, p.pontos]}, height: "600px" %>
  
</div>